[package]
name = "thailand-driving-exam-questions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
minidom = "0.15.1"
regex = "1.7.1"
